# Generated by Django 6.0.6 on 2026-06-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='slug',
        ),
    ]
