# Generated by Django 6.0.6 on 2026-06-12 19:24

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatgroup_is_private_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
