# Generated by Django 6.0.6 on 2026-06-13 10:25

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatgroup_admin_chatgroup_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
